name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - id: 'checkout'
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Build the project
      - name: Build Project
        run: |
          yarn build
          echo "The current working directory is: $(pwd)"
          echo "The absolute path of the build directory is: $(pwd)/build"

  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - id: 'checkout'
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Upload files to Google Cloud Storage using upload-cloud-storage
      - id: 'upload-folder'
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: '/home/runner/work/NetflixClone/NetflixClone/build/'  # Caminho absoluto da pasta build
          destination: '${{ secrets.GCP_BUCKET }}'

