name: Deploy to GCP

on:
  push:
    branches:
      - master  # Alterado para "master" conforme o Bitbucket Pipeline

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: |
          yarn install

      - name: Build project
        run: |
          yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: build
          path: ./build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3  # Atualizado para v3
        with:
          name: build
          path: ./build

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_KEYFILE }}"  # Usando a chave de autenticação do GCP

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GCP
        run: |
          gsutil -m rsync -r ./build/ gs://netflixclone111/
        
