name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:23-alpine

    steps:
      # Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v2

      # Instalar dependências
      - name: Install dependencies
        run: |
          yarn install

      # Executar build
      - name: Build project
        run: |
          yarn build

      # Persistir a pasta build para ser usada nas próximas etapas
      - name: Cache build folder
        uses: actions/cache@v3
        with:
          path: ./build
          key: build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            build-

      # Deploy para o Google Cloud Storage
      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          bucket: netflixclone111
          path: './build/**/*'  # Caminho dos arquivos a serem enviados
          destination: 'path/to/destination/'  # Defina o caminho de destino no bucket
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_API_KEYFILE }}
