name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      # Instalar dependências
      - name: Install dependencies
        run: yarn install

      # Construir o projeto
      - name: Build the project
        run: yarn build

      # Salvar os artefatos da build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

      # Baixar os artefatos da build para o ambiente atual
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      # Verificar os arquivos
      - name: List files in build directory
        run: ls -la build

      # Fazer upload para o Google Cloud Storage
      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: 'build/**'
          destination: 'gs://netflixclone111/'
          project_id: 'daniel-web-444219'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEYFILE }}

