name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      # Instalar dependências
      - name: Install dependencies
        run: yarn install

      # Construir o projeto
      - name: Build the project
        run: yarn build

      # Listar arquivos no diretório build
      - name: List files in build directory
        run: ls -la build

      # Decodificar a chave Base64
      - name: Decode GCP credentials from Base64
        run: echo "${{ secrets.GCP_KEYFILE_BASE64 }}" | base64 --decode > gcloud-credentials.json

      # Fazer upload para o Google Cloud Storage
      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: './build/*'  # Caminho correto
          destination: 'gs://netflixclone111/'
          project_id: 'daniel-web-444219'
          gzip: true
          resumable: true
          parent: true
          concurrency: 100
          gcloudignore_path: .gcloudignore
          process_gcloudignore: false  # Desabilitar o ignore para depuração
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcloud-credentials.json
