name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Build the project
      - name: Build Project
        run: yarn build

      # List build directory contents (for debugging)
      - name: List Build Directory
        run: |
          echo "Listing the contents of the build directory:"
          ls -l ./build

  deploy:
    name: Deploy to Google Cloud Storage
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Install Google Cloud SDK
      - name: Install Google Cloud SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      # Check if build directory exists
      - name: Check Build Directory
        run: |
          if [ ! -d "./build" ]; then
            echo "Error: Build directory './build' does not exist."
            exit 1
          fi
          echo "Build directory exists. Listing contents:"
          ls -l ./build

      # Upload files to Google Cloud Storage using gsutil
      - name: Upload to GCS
        run: |
          gsutil -m rsync -r ./build gs://${{ secrets.GCP_BUCKET }}
