name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:23-alpine

    steps:
      # Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v2

      # Instalar dependências
      - name: Install dependencies
        run: |
          yarn install

      # Executar build
      - name: Build project
        run: |
          yarn build

      # Verificar se a pasta build foi criada
      - name: Check build folder
        run: |
          ls -R ./build

      # Persistir pasta build no workspace
      - name: Persist build folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp -r ./build $GITHUB_WORKSPACE/artifacts/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout do código-fonte para restaurar contexto do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Restaurar a pasta build do workspace
      - name: Restore build folder
        run: |
          cp -r $GITHUB_WORKSPACE/artifacts/build ./build
          ls -R ./build

      # Deploy para o Google Cloud Storage
      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          bucket: netflixclone111
          path: './build/**/*'
          destination: 'path/to/destination/'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEYFILE }}
